name = "lean-astar"
version = "0.1.0"
defaultTargets = ["LeanAStar"]
testDriver = "LeanAStarTest"

[[lean_lib]]
name = "LeanAStar"

[[lean_lib]]
name = "LeanAStarTest"

[[lean_exe]]
name = "LeanAStarTest"

[[require]]
name = "BinaryHeap"
git = "https://github.com/soulsource/BinaryHeap"
revision = "a2fcff2dbe3561e3a51b810b3f0577ba99ef5e78"